
services:
  # Dịch vụ Database
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: realtime_board_postgres:latest
    container_name: realtime_board_container
    restart: always          
    environment:
      POSTGRES_USER: admin     
      POSTGRES_PASSWORD: Annam123@123 
      POSTGRES_DB: realtime_board  
    ports:
      - "5434:5432"           
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  # (Tùy chọn) Giao diện quản lý DB - pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: realtime_board_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"              
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: realtime_board_backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      LOG_FORMAT: json
      LOG_LEVEL: info
      RUST_LOG: info
    ports:
      - "3002:3000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
