
services:
  # Dịch vụ Database
  db:
    image: postgis/postgis:17-3.5
    container_name: realtime_board_container
    restart: always          
    environment:
      POSTGRES_USER: admin     
      POSTGRES_PASSWORD: Annam123@123 
      POSTGRES_DB: realtime_board  
    ports:
      - "5434:5432"           
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  # (Tùy chọn) Giao diện quản lý DB - pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: realtime_board_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"              
    depends_on:
      - db

volumes:
  postgres_data: